### ISSUE TITLE
oscr website does not have a valid site certificate

### ISSUE THREAD

**Issue by vinny2020** [Open-Source-for-Civil-Rights/oscr-website#2]
Nowadays there are places where you can get free or dirt cheap secure SSL certificates. RIght now users will get a security warning in their browser that will scare some people away from the site

**Comment by caelinsutch** [comment]
Yeah so this is a problem with Firebase Hosting (which I'm using). The recommended solution is to just [wait](https://stackoverflow.com/questions/39158677/firebase-hosting-using-custom-domain-has-ssl-cert-pointing-to-firebase-com)

**Comment by caelinsutch** [comment]
Resolved!
